pipeline {
      agent any
	  
	  stages {
	      stage ('compile stage') {_
		       withmaven(maven : 'maven_3_8_2') {
			      sh 'mvn clean compile'
			
          	}
		}
     }
	  
	  stages {
	      stage ('testing stage') {_
		       withmaven(maven : 'maven_3_8_2') {
			      sh 'mvn test'
			
          	}
		}
     }
	  stages {
	      stage ('deployment') {_
		       withmaven(maven : 'maven_3_8_2') {
			      sh 'mvn deploy'
			
          	}
		}
     }
	}
   }
